export type Priority = 'normal' | 'non-urgent' | 'urgent'
export type Importance = 'low' | 'normal' | 'high'

export interface RequiredHeaders {
  /**
   * The email address of the sender. Can include a display name.
   * @example '"John Doe" <john.doe@example.com>'
   * @example 'newsletter@company.com'
   */
  From: string

  /**
   * The email addresses of the recipients. Can include display names.
   * Multiple addresses can be separated by commas.
   * @example '"Jane Smith" <jane.smith@example.com>, support@company.com'
   * @example 'team@company.com'
   */
  To: string

  /**
   * The subject line of the email.
   * @example 'Your Order Confirmation #12345'
   * @example 'Meeting Notes - Q1 Planning'
   */
  Subject: string
}

export interface OptionalHeaders {
  /**
   * The email address to reply to, if different from the From address.
   * Can include a display name.
   * @example '"Customer Support" <support@company.com>'
   * @example 'no-reply@company.com'
   */
  ReplyTo?: string

  /**
   * Carbon copy recipients. Multiple addresses can be separated by commas.
   * @example '"Project Team" <team@company.com>, manager@company.com'
   */
  Cc?: string

  /**
   * Blind carbon copy recipients. Multiple addresses can be separated by commas.
   * @example 'archive@company.com, auditor@company.com'
   */
  Bcc?: string

  /**
   * The priority level of the message.
   */
  Priority?: Priority

  /**
   * The importance level of the message.
   */
  Importance?: Importance
}

/**
 * Headers related to content and MIME types.
 */
export interface ContentHeaders {
  /**
   * The MIME type of the content
   * @example 'text/plain'
   * @example 'image/jpeg; name=photo.jpg'
   * @example 'text/html; charset=UTF-8'
   */
  'Content-Type': string
  /**
   * The encoding used for the content
   * @example 'base64' - For binary content like images
   * @example '7bit' - For plain ASCII text
   * @example '8bit' - For text with special characters
   * @example 'quoted-printable' - For text with special characters
   */
  'Content-Transfer-Encoding': 'quoted-printable' | 'base64' | '7bit' | '8bit'
  /**
   * Base URL for resolving relative URLs in the email content
   * @example 'https://example.com/email/'
   */
  'Content-Base'?: string
  /**
   * Content classification for filtering (less common)
   * @example 'newsletter'
   */
  'Content-Class'?: string
  /**
   * Human-readable description of the content
   * @example 'Monthly Newsletter - January 2024'
   */
  'Content-Description'?: string
  /**
   * Duration of audio/video content in seconds (specific use cases)
   * @example '120'
   */
  'Content-Duration'?: string
  /**
   * Unique identifier for content parts in multipart messages (essential for inline content)
   * @example '<part1.12345@example.com>'
   */
  'Content-ID'?: string
  /**
   * Natural language of the content
   * @example 'en-US'
   */
  'Content-Language'?: string
  /**
   * URI for retrieving the content (less common)
   * @example 'https://example.com/newsletter/january-2024.html'
   */
  'Content-Location'?: string
  /**
   * How the content should be displayed or handled (inline or attachment)
   * @example 'attachment; filename="document.pdf"'
   * @example 'inline'
   */
  'Content-Disposition'?: string
  /**
   * MD5 checksum of the content for integrity verification
   * @example 'Q2hpY2tlbiBTd2FpcA=='
   */
  'Content-MD5'?: string
  /**
   * Specifies a range of content (for partial content)
   * @example 'bytes 0-499/1234'
   */
  'Content-Range'?: string
  /**
   * Allows for versioning of a specific MIME part (less common)
   */
  'Content-Version'?: string
  /**
   * Provides information about the features of the content
   */
  'Content-features'?: string
  /**
   * Custom application-specific headers
   * @example 'X-My-Custom-Header: Some Value'
   */
  [key: `X-${string}`]: string | undefined
}

/**
 * Headers for message identification and threading.
 * Note: Message-ID is typically generated by the email service.
 */
export interface MessageIdentificationHeaders {
  /**
   * Message ID being replied to
   * @example '<1234@example.com>'
   */
  'In-Reply-To'?: string
  /**
   * Chain of message IDs in the conversation
   * @example '<1234@example.com> <5678@example.com>'
   */
  'References'?: string
  /**
   * Thread index for conversation grouping
   * @example 'AQHSR5cz6k2WzYwM'
   */
  'Thread-Index'?: string
  /**
   * Subject line used for threading
   * @example 'Re: Project Discussion'
   */
  'Thread-Topic'?: string
}

/**
 * Headers related to email routing and delivery.
 * Note: Most routing headers are set by mail transfer agents.
 */
export interface RoutingHeaders {
  /**
   * Address for error notifications
   * @example 'errors@example.com'
   */
  'Errors-To'?: string
  /**
   * Original recipient address before forwarding
   * @example 'jane.doe@olddomain.com'
   */
  'Original-Recipient'?: string
}

export interface ListHeaders {
  /**
   * URL of the mailing list archive
   * @example 'https://example.com/list/archive'
   */
  'List-Archive'?: string
  /**
   * URL for mailing list help
   * @example 'mailto:list-help@example.com'
   */
  'List-Help'?: string
  /**
   * Unique identifier for the mailing list
   * @example '<announcements.example.com>'
   */
  'List-Id'?: string
  /**
   * Contact information for list owner
   * @example 'mailto:owner-list@example.com'
   */
  'List-Owner'?: string
  /**
   * Address for posting to the list
   * @example 'mailto:list@example.com'
   */
  'List-Post'?: string
  /**
   * URL for list subscription
   * @example 'mailto:list-subscribe@example.com'
   */
  'List-Subscribe'?: string
  /**
   * URL for list unsubscription
   * @example 'mailto:list-unsubscribe@example.com'
   */
  'List-Unsubscribe'?: string
  /**
   * HTTP POST URL for one-click unsubscribe
   * @example 'https://example.com/unsubscribe'
   */
  'List-Unsubscribe-Post'?: string
}

export interface NotificationHeaders {
  /**
   * Options for disposition notifications
   * @example 'X-RCPT-TO=user@example.com'
   */
  'Disposition-Notification-Options'?: string
  /**
   * Address to send read receipts
   * @example 'read-receipts@example.com'
   */
  'Disposition-Notification-To'?: string
  /**
   * Address for return receipts
   * @example 'receipts@example.com'
   */
  'Return-Receipt-To'?: string
}

/**
 * Headers for user preferences and client information.
 * Note: Some headers like User-Agent are typically set by the email client.
 */
export interface PreferenceHeaders {
  /**
   * Preferred language for auto-responses
   * @example 'en-US, fr-FR;q=0.7'
   */
  'Accept-Language'?: string
  /**
   * Sender's organization
   * @example 'Example Corp.'
   */
  'Organization'?: string
  /**
   * Message sensitivity level
   * @example 'company-confidential'
   */
  'Sensitivity'?: string
  /**
   * Commercial email solicitation flag
   * @example 'N'
   */
  'Solicitation'?: string
}

export interface MetadataHeaders {
  /**
   * Additional notes about the message
   * @example 'Automated response from support system'
   */
  Comments?: string
  /**
   * Search keywords for the message
   * @example 'invoice, payment, january'
   */
  Keywords?: string
  /**
   * Delivery precedence
   * @example 'bulk'
   */
  Precedence?: string
}
